### ISSUE TITLE
error when pushing to NPR for NPR one audio

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#10]
when I "push to NPR" to send the audio to NPR One, I get this error message. I have only done this once so far with this link: http://indianapublicmedia.org/news/opponents-bobcat-hunting-controversial-proposals-call-information-143533/

Error message: 

An error occurred when pushing this post to NPR

**Comment by eobanb** [comment]
Becca, try it again. There was an upload file size limit of 2 MB. It's been increased to 32 MB now.

**Comment by eobanb** [comment]
I have an open ticket with NPR digital support about this now.

**Comment by eobanb** [comment]
This is finally fixed
