### ISSUE TITLE
unpublished stories still displayed in lists

### ISSUE THREAD

**Issue by aaronburatti** [indianapublicmedia/indianapublicmedia-web#103]
Several formats, e.g. up next stories, only check for last published date when deciding what stories to display. Find way to make sure the stories aren't displayed if they arent published.

**Comment by eobanb** [comment]
This also happens with story-paths-index

**Comment by aaronburatti** [comment]
@eobanb have you seen this or heard of this happening on any index pages?

**Comment by eobanb** [comment]
@aaronburatti not that I have noticed so far.

**Comment by aaronburatti** [comment]
resolved
