### ISSUE TITLE
/theinbox/ (and indiandroid) design update to add 300x250 corp dev ad

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#116]
The INbox design should be updated to accommodate a 300x250 google ad manager ad.

**Comment by eobanb** [comment]
@aaronburatti can this be done by the end of July?

**Comment by aaronburatti** [comment]
@eobanb probably. I'll talk to payton and whip something up

**Comment by aaronburatti** [comment]
This is all mapped out, we just need the ads to use

**Comment by aaronburatti** [comment]
@eobanb Idk if you ever saw my comment here

**Comment by aaronburatti** [comment]
implemented
