### ISSUE TITLE
title tags should always be a consistent format

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#118]
Format of home pages' title tags should always be: `Section Name - Indiana Public Media`

Format of sub pages' title tags should always be: `Pagename | Section Name - Indiana Public Media`

### Examples:

News homepage: `News - Indiana Public Media`

Radio homepage: `WFIU Public Radio - Indiana Public Media`

News article: `Indiana To Join 31 States In Nurse Licensure Compact | News - Indiana Public Media`

INbox post: `‘The Railroad Helped Make Us’: Monon-Inspired Exhibit Pulls into French Lick | The INbox - Indiana Public Media`

Jobs page: `Careers and Internships | About - Indiana Public Media`

Station blog post: `Bob Zaltsberg to Join WFIU | Blog - Indiana Public Media`

**Comment by aaronburatti** [comment]
potentially resolved. Bears watching

**Comment by eobanb** [comment]
This does not appear to be fixed yet on a number of sections. Examples:

https://indianapublicmedia.org/theinbox/revived-ruins-in-indys-holliday-park.php

https://indianapublicmedia.org/events/station-events/brickyard-vintage-racing-invitational.php

https://indianapublicmedia.org/indiandroid/the-history-of-hoosier-cryptids.php

https://indianapublicmedia.org/services/studio-production.php

https://indianapublicmedia.org/porchlight/time.php

https://indianapublicmedia.org/users/mchilla.php

Station blog posts have two (different/conflicting) `<title>` tags:

https://indianapublicmedia.org/blog/wtiu-earns-five-natas-lower-great-lakes-emmy-awards.php

**Comment by aaronburatti** [comment]
This is being rolled, at least partially, into the section data/folder metadata set ticket #129

**Comment by aaronburatti** [comment]
Improved. Bears watching. The folder metadata will be rolled out in a full way and eventually replace format html meta tag variations, but is not ready for production yet

**Comment by aaronburatti** [comment]
Vastly improved, ready for testing

**Comment by aaronburatti** [comment]
Moved so far along I'm closing it
