### ISSUE TITLE
all sections must have author meta tag

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#120]
Currently author meta tags appear in the markup of /news/ and /arts/, but no other sections. These should be included with /theinbox/, /indiandroid/, and all other future sections we set up in Cascade.

**Comment by aaronburatti** [comment]
theinbox and indianadroid done. @eobanb Besides the radio sections we are launching now, what other sections need this?

**Comment by eobanb** [comment]
I think /noonedition/ and /journeyindiana/ would be the main other ones (besides all the radio program sites).

This should be for individual posts only (so no front pages, topic pages, etc), and only 'content' areas, so nothing on /about/, /services/, /support/, etc.

**Comment by aaronburatti** [comment]
resolved
