### ISSUE TITLE
'view more stories' button(s)

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#125]
Let's add the 'view more stories' feature to the Noon Edition front page

**Comment by eobanb** [comment]
After more thought, this is something suitable for a lot of different pages, particularly anywhere we have a single main column of content.

**Comment by aaronburatti** [comment]
Update for Arts & Culture: There are several duplicate posts as if people recently or are still making redirect posts. We need to be sure this practice has stopped entirely or does stop before implementing this

**Comment by aaronburatti** [comment]
implemented in single column list view radio programs

**Comment by eobanb** [comment]
@aaronburatti I think you could go ahead and implement this for Arts now
