### ISSUE TITLE
/arts/ automatically display new posts from certain other sections

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#126]
The /arts/ front page format should be reconfigured to display not only new arts posts, but also all new posts from these sections...

- /afterglow/
- /ethergame/
- /harmonia/
- /theinbox/
- /indiandroid/
- /journeyindiana/
- /nightlights/
- /poetsweave/
- /porchlight/
- /profiles/

_except_ if any of the following conditions are true:

- the post is tagged 'no-arts'
- the post does not have a photo

Note: some minor additional styling and labelling may be warranted to categorize/label these posts.

This can optionally be implemented incrementally, as new sections are moved from WP to Cascade. Or, all at once (after all of the above sections are live in Cascade).

**Comment by eobanb** [comment]
soft deadline is end of July

**Comment by aaronburatti** [comment]
This is going to wait till all of these sections are published from cascade

**Comment by eobanb** [comment]
All of these are on Cascade now except Profiles and Night Lights, which will both launch very soon. So I'd start looking at this more next week.

**Comment by eobanb** [comment]
Note: this should apply to / and /radio/ as well (where recent arts posts are shown).
