### ISSUE TITLE
/fridayzone/ -> Cascade

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#132]
/fridayzone/ is still on Wordpress and should be moved to Cascade. This is more of an August (or perhaps even September) project as it will entail more of a redesign.

**Comment by eobanb** [comment]
This is going to be _mostly_ be based on the Journey Indiana template.

**Comment by aaronburatti** [comment]
This is effectively resolved

**Comment by aaronburatti** [comment]
Whatever happened to this? This is like the last thing in the "migration" project

**Comment by eobanb** [comment]
This is still on-hold while the new graphics designer gets up to speed.
