### ISSUE TITLE
firefox browser flashing a page twice

### ISSUE THREAD

**Issue by aaronburatti** [indianapublicmedia/indianapublicmedia-web#133]
Some pages seem to flash, or load, twice in firefox. No other browser seems to have this issue

**Comment by aaronburatti** [comment]
Here's an interesting forum post about it: https://groups.google.com/forum/#!topic/mozilla.support.firefox/MRo1snUdoWo

two posts near the end suggest some possible sources of the issue including " a URL Rewriting Rule in a web.config file" and " Firefox tries to load pages over http2, and chrome is still loading over http/1.1" among others

**Comment by eobanb** [comment]
@aaronburatti not urgent, but can you test this with Firefox on sitehost?

**Comment by eobanb** [comment]
I've noticed this seems to still happen on Sitehost. It only seems to happen on some/all Cascade pages so I suspect it has something to do with how some css or js is structured.

**Comment by aaronburatti** [comment]
Not resolvable
