### ISSUE TITLE
jplayer - reconfigure to play pre-roll (for all mp3s on site)

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#135]
jplayer should be reconfigured to be able to play a pre-roll mp3 file (very short, approx. 5 seconds). Go live sometime in August

**Comment by aaronburatti** [comment]
@eobanb These pre-rolls will be replaceable with any mp3 we select?

**Comment by eobanb** [comment]
Correct, similar to how the streaming player is currently configured. This is not something you need to work on however (at least for now)

**Comment by aaronburatti** [comment]
Sure. I have a good grasp on my pipeline, just trying to understand the issue. Are we also going to move towards underwriter breaks in the middle of programs? or at the end?

**Comment by eobanb** [comment]
Just pre-rolls for the foreseeable future. Middle is not feasible/desirable. Post-roll is possible with jplayer, but not really a priority right now.

**Comment by eobanb** [comment]
Almost done with this one...

**Comment by aaronburatti** [comment]
resolved
