### ISSUE TITLE
/arts/ - double quotes in titles/teasers causing Velocity errors

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#139]
May not be limited to /arts/ ... probably has to do with the new meta fields implementation.

**Comment by aaronburatti** [comment]
This is not an issue if the single quotations are used (''). Essentially, there can only be one set of quotation marks inside the html meta tags which use the title and teaser more efficiently. There is no perfect, everyone gets to do what they want with titles and teasers, solution either.

**Comment by aaronburatti** [comment]
resolved.
