### ISSUE TITLE
cannot upload audio greater than 2mb

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#14]
Wordpress says the maximum file upload size is 32MB but in reality it will not accept files larger than about 2MB (I don't know exactly)

**Comment by eobanb** [comment]
When's the last time you tried this? This is the same problem (as far as I know) as the image size problem described [in this issue](https://github.com/eobanb/indianapublicmedia-wp/issues/9). Dan said he had changed the max upload to 32 MB yesterday at around 4:30pm.

**Comment by rebmthom** [comment]
I tried less than an hour ago. And I'm still getting the error for large photos as well.

**Comment by eobanb** [comment]
Duplicate of #9
