### ISSUE TITLE
/feeds/ - RSS output formats should ensure all mp3 enclosures are https

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#140]
Occasionally a podcast RSS feed will contain an `<enclosure>` element with a http:// URL, rather than https:// . It is a requirement of both Apple and NPR that all mp3 URLs be https, so any/all Cascade formats for generating RSS XML should ensure this, even if the URL entered in the field by a user begins with http:// .

**Comment by aaronburatti** [comment]
this _should_ be taken care of
