### ISSUE TITLE
audio transcript field + UI

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#144]
IU's accessibility policies say we should provide transcripts for all new audio on our website.

To comply with this policy, we should begin by creating a new field in any data definition used by pages with audio. Producers will use this field to attach the transcript for mp3 audio.

The second half of the equation: the page format should output the transcript in a hidden HTML element, which becomes visible (jquery) if a user hits a 'view transcript' link.

Questions:

- this DD field should probably be plain text. Any pros/cons to rich text?
- Any other considerations to make here?

**Comment by aaronburatti** [comment]
implemented. no complaints
