### ISSUE TITLE
migration - rtvdigit webserve to IU sitehosting

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#153]
Details forthcoming.

**Comment by eobanb** [comment]
Note: RTVS also owns two other group accounts (and webserve accounts) - wfiu, and radiotv. **These will also have to be moved.**

**Comment by eobanb** [comment]
Checklist for migration:

- php includes - ( @eobanb and @aaronburatti )
- email logging - ( @aaronburatti )
- cron scripts archive pages - ( @aaronburatti )
- rsync data for BTi and Vantage ( mostly @eobanb )
- recaptcha - ( @aaronburatti )
- do a final rsync - ( @eobanb )

other:

- archive ~radiotv and ~wfiu accounts - ( @eobanb )

**Comment by aaronburatti** [comment]
done
