### ISSUE TITLE
audio transcript audit tool

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#159]
We should create a simple audit tool inside of Cascade in order to track web posts with audio, but no valid transcript attached. Simple configuration options might include:

- Timeframe (beginning / end)
- Threshold for what constitutes a valid transcript vs. a placeholder (I.e. number of characters)
- Whether to check the entire site, or just one section

Ideally, the tool would output a simple table with columns for Title, URL, author, and number of characters in the transcript field. From a technical standpoint it could function in a similar manner to the quarterly report CSV tool.

This should be a small project for the December timeframe _after_ Cascade and Sitehost migrations are done.

**Comment by aaronburatti** [comment]
first version is up and working
