### ISSUE TITLE
/radio/ (and /tv/ ) - lightboxes

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#160]
The tool currently used to manage banners should be extended to add lightboxes. Suggested solution:

- Inside Cascade, add a new option for 'type': banner, or lightbox, as other existing options for start/end, image URL, and clickthrough URL also apply here. Subsequently, the existing banner implementation can be changed to use only items of type: banner
- A mobile-friendly and configurable lightbox JS library should be researched, preferably using jquery and not creating additional dependencies on other js toolkits if possible. This should be deployed to the /radio/ and /tv/ homepages, and display item of type: lightbox
- This should be deployed and thoroughly tested in the Nov 11-15 timeframe, with a deadline of Nov 22 (this is when calendar year-end fundraising campaigns begin).

**Comment by aaronburatti** [comment]
implemented
