### ISSUE TITLE
/eartheats/ - general cleanup

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#167]
Example: https://indianapublicmedia.org/eartheats/planting-future.php

Some issues:

* Episode segments are absent
* 'Music on this episode' formatting
* Photo caption / credit formatting
* 'About Earth Eats' text in sidebar is absent

There are likely other Earth Eats posts with similar issues.

**Comment by aaronburatti** [comment]
This should be done
