### ISSUE TITLE
newscast audio is not being added to NPR One

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#17]

**Comment by rebmthom** [comment]
I think this is fixed now? I'm seeing newscasts from last week on our NPR One stats in station analytics.

**Comment by eobanb** [comment]
Sorry for the label mess, I confused this with a different issue. Correct me if I'm wrong, but this is now fixed.

**Comment by rebmthom** [comment]
Yes, this is fixed.
