### ISSUE TITLE
scheduled publishes don't trigger index

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#170]
Aaron Cain scheduled a /profiles/ post to go live Sunday but it apparently did not trigger an auto-publish of the section's index page. Is this feasible to fix?

**Comment by aaronburatti** [comment]
@eobanb You should ask him more about this. I just tested a scheduled publish and it published the profiles section index page

**Comment by eobanb** [comment]
I've asked him to keep an eye on it. Closing for now
