### ISSUE TITLE
/amomentofscience/ (and others?) deal with &#160 chars

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#176]
On many older posts imported from WP, characters such as `&#160;` are being incorrectly encoded/mapped and displaying as Â. This occurs on AMOS and may be happening on other posts as well, particularly at the end of words or phrases inside `<em>` tags.

These should be removed and replaced with a regular space character.

**Comment by aaronburatti** [comment]
This is being fixed as we speak for AMOS. Lets keep our eye on it and look out for other sections that may need it too
