### ISSUE TITLE
/nightlights/ archives 2020

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#178]
2020 archive page exists but not correctly populated.

https://indianapublicmedia.org/archive/nightlights/archive-2020.php

Navigation also must be updated.

Similar problem may exist with other sections.

**Comment by eobanb** [comment]
Issue also exists for /harmonia/ and /eartheats/

**Comment by aaronburatti** [comment]
These pages are correct now and the nav should be up to date
