### ISSUE TITLE
/news/ stories from BL-RTVS-WEBS.news don't re-publish correctly

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#181]
Example:

https://indianapublicmedia.org/news/federal-grant-delivers-increase-funds-treat-opioid-abuse-127552.php

https://sites.wcms.iu.edu/entity/open.act?id=21ea8874814f4e1069ba397530cd4997&type=page

**Comment by aaronburatti** [comment]
This is resolved
