### ISSUE TITLE
/nightlights/ odd characters

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#182]
Example:

https://indianapublicmedia.org/nightlights/road-stardust-hoagy-carmichael-bix-beiderbecke-1924.php

Character sequence that appears is:

`â€¦`

This should be mass-fixed across any/all NL posts with this character sequence.

**Comment by aaronburatti** [comment]
should be resolved

**Comment by eobanb** [comment]
Unfortunately there seems to be some other posts with a similar character sequence I did not notice before. Example:

https://indianapublicmedia.org/nightlights/journey-chico-hamilton-1960s.php

Sequence is: `â€™` but should be an apostrophe.

**Comment by eobanb** [comment]
A few more issues with this; example:

https://indianapublicmedia.org/nightlights/we-shall-overcome-civil-rights-jazz.php

Character sequences are `â€œ` and `â€`

Given that all of these character sequences seem to start with `â€` that might be a good string to check for, in case there are still more variations.

**Comment by aaronburatti** [comment]
The problem is that these characters don't show up anywhere that is accessible by WS.
