### ISSUE TITLE
/eartheats/ some older posts missing original photo

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#188]
Some types of certain older EE posts are missing their original photo, mainly recipes and some news posts. Examples:

https://indianapublicmedia.org/eartheats/fashioned-potato-latkes-2.php
https://indianapublicmedia.org/eartheats/food-energy-weather-woes-growers-eggplant.php
https://indianapublicmedia.org/eartheats/broiled-miso-eggplant-tofu-salad.php
https://indianapublicmedia.org/eartheats/fuel-whats-dinner.php

**Comment by aaronburatti** [comment]
@eobanb these should really be seperate issues for ease of tracking
