### ISSUE TITLE
/news/ duplicate stories

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#189]
Example:

https://indianapublicmedia.org/archive/news/news-archive-2017-12.php

**Comment by aaronburatti** [comment]
I'm going to try to solve this before the /news author accreditation because getting rid of duplicates may remove up to 1/6th of pages in .news which would really speed up any wholesale fixes to .news

**Comment by aaronburatti** [comment]
I think this issue may be resolved actually

**Comment by aaronburatti** [comment]
resolved

**Comment by aaronburatti** [comment]
This is is like the zombie ticket, just keeps coming back. I believe it is resolved. Clear your browser cache of the page before reopening this ticket
