### ISSUE TITLE
Podcasts not updating

### ISSUE THREAD

**Issue by atcain** [indianapublicmedia/indianapublicmedia-web#19]
No program content created since the restoration of the main site (via Wordpress) seems to be showing up as new podcasts, even though the audio for those programs are now streaming without incident.

**Comment by eobanb** [comment]
Can you link an example?

**Comment by atcain** [comment]
I can link an example of a Profiles program which has an intact post, and intact streaming audio (as of your fix this morning), but that still does not show up as a downloadable podcast in searches of iTunes, TuneIn, etc:

https://indianapublicmedia.org/profiles/kathleen-hall-jamieson/

Aaron



On Mar 29, 2018, at 2:54 PM, Eoban Binder <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you link an example?

**Comment by eobanb** [comment]
I just checked on the Profiles podcast on iTunes, and the latest episode (with Kathleen Hall Jamieson) does seem to appear and play back just fine:

https://itunes.apple.com/us/podcast/profiles/id153368305?mt=2

**Comment by atcain** [comment]
Odd. Still won’t work for me. Yalie Kamara is the last one that I can access. Perhaps it’s my iPhone that is the culprit.

On Mar 29, 2018, at 4:08 PM, Eoban Binder <notifications@github.com<mailto:notifications@github.com>> wrote:


I just checked on the Profiles podcast on iTunes, and the latest episode (with Kathleen Hall Jamieson) does seem to appear and play back just fine:

https://itunes.apple.com/us/podcast/profiles/id153368305?mt=2

**Comment by eobanb** [comment]
Keep me posted, but for now I'm going to close this.
