### ISSUE TITLE
/news/ stories should show guest author bylines

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#190]
This is similar to #183 that we saw with AMOS; many older News stories show 'Indiana Public Media News Staff' rather than the guest author contents. Examples:

https://indianapublicmedia.org/news/bill-lead-polling-places.php

https://indianapublicmedia.org/news/fda-approves-implanted-medication-opioid-addiction-99709.php

https://indianapublicmedia.org/news/52-million-sr-46-road-project-spencer-completed.php

**Comment by aaronburatti** [comment]
should be all taken care of

**Comment by eobanb** [comment]
The three examples above all still read 'Indiana Public Media News Staff' ?

**Comment by aaronburatti** [comment]
There are 40 pages in the .news queue. Lets look at it tomorrow

**Comment by aaronburatti** [comment]
All of these stories have the correct byline and are in the publish queue already

**Comment by eobanb** [comment]
Unfortunately there are still many news stories with generic bylines. Examples:

https://indianapublicmedia.org/news/live-experts-talk-foreign-policy-issues-president-face-106086.php

https://indianapublicmedia.org/news/report-clarity-school-vouchers-debate-122378.php

https://indianapublicmedia.org/news/hamilton-southeastern-schools-spend-300k-year-enroll-4yearolds-153882.php

https://indianapublicmedia.org/news/overcrowding-funding-addressed-sheriffs-table-148048.php

https://indianapublicmedia.org/news/study-paternal-depression-common-152981.php

https://indianapublicmedia.org/news/holcomb-signs-workforce-development-bills-business-concerns-143764.php

https://indianapublicmedia.org/news/state-fair-attendance-down-5,-but-breaks-weekday-record.php

https://indianapublicmedia.org/news/developers-host-public-discussions-bloomington-kmart-location-151658.php

https://indianapublicmedia.org/news/sen-young-anxious-tariffs-strategy-153722.php

https://indianapublicmedia.org/news/george-taliaferro,-iu-legend-first-african-american-taken-in-nfl-draft,-dies-at-91.php

https://indianapublicmedia.org/news/weather-updates-flash-flood-warning,-mccsc-releasing-early.php

https://indianapublicmedia.org/news/ernie-pyle-receive-national-day-133768.php

**Comment by eobanb** [comment]
Status on this one @aaronburatti ?

**Comment by aaronburatti** [comment]
@eobanb still working on it

**Comment by aaronburatti** [comment]
This should be resolved

**Comment by eobanb** [comment]
It is resolved yet; there are still many posts unfixed.

Example 1

Archived WP version w/ byline:
https://web.archive.org/web/20190731043741/https://indianapublicmedia.org/news/hamilton-southeastern-schools-spend-300k-year-enroll-4yearolds-153882/

Live version with generic:
https://indianapublicmedia.org/news/hamilton-southeastern-schools-spend-300k-year-enroll-4yearolds-153882.php

Example 2

Archived WP version w/ byline:
https://web.archive.org/web/20190704123530/https://indianapublicmedia.org/news/study-paternal-depression-common-152981/

Live version with generic:
https://indianapublicmedia.org/news/study-paternal-depression-common-152981.php

Example 3

Archived WP version w/ byline:
https://web.archive.org/web/20190705013126/https://indianapublicmedia.org/news/developers-host-public-discussions-bloomington-kmart-location-151658/

Live version with generic:
https://indianapublicmedia.org/news/developers-host-public-discussions-bloomington-kmart-location-151658.php

Example 4

Archived WP version w/ byline:
https://web.archive.org/web/20190704092957/https://indianapublicmedia.org/news/sen-young-anxious-tariffs-strategy-153722/

Live version with generic:
https://indianapublicmedia.org/news/sen-young-anxious-tariffs-strategy-153722.php

Example 5

Archived WP version w/ byline:
https://web.archive.org/web/20190705094427/https://indianapublicmedia.org/news/iu-researchers-work-3dprinting-organs-151159/

Live version with generic:
https://indianapublicmedia.org/news/iu-researchers-work-3dprinting-organs-151159.php

etc.

**Comment by aaronburatti** [comment]
All of the above issues are post June '18. I, for whatever reason, don't have that WP XML exported from then. I have a continuous timeline up until June '18.

**Comment by aaronburatti** [comment]
Update: This issue has also ran into the 80/20 rule. Once the phantom node issue is solved this can be solved. The scripts and techniques for this exist but are on hold so this will be resolved quickly once it can be worked on

**Comment by aaronburatti** [comment]
update 6/8: I am attempting to fix this as i re-import pages into Cascade, as the script for doing this has been built.

**Comment by aaronburatti** [comment]
This should be close-able soon, I believe when the new news archive folders are publishable

**Comment by aaronburatti** [comment]
This is also a necromanced ticket. I believe it is currently resolved
