### ISSUE TITLE
/news/ a number of stories that appear in date archives return 404

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#191]
Examples:

https://indianapublicmedia.org/news/weekend-storms-damage-tippecanoe-schools-delay.php

https://indianapublicmedia.org/news/video-watch-indiana-newsdesk-january-30-2015.php

https://indianapublicmedia.org/news/indiana-spared-years-blizzard-1978.php

https://indianapublicmedia.org/news/indy-500-cash-prize-visualized-99704.php

https://indianapublicmedia.org/news/woman-dies-swimming-cataract-falls-99696.php

https://indianapublicmedia.org/news/study-transport-snake-turtle-99691.php

**Comment by aaronburatti** [comment]
This should be resolved

**Comment by eobanb** [comment]
All the above examples still 404, unfortunately

**Comment by aaronburatti** [comment]
I see. These will never show a page because they should have never been in the archives to begin with. These links are supposed to 404 and they should now no longer be showing up in the archives. Thats why i closed this.

**Comment by eobanb** [comment]
These were definitely published stories though...

https://web.archive.org/web/20160104122641/http://indianapublicmedia.org:80/news/video-watch-indiana-newsdesk-january-30-2015-77580/

https://web.archive.org/web/20161021144007/http://indianapublicmedia.org:80/news/indiana-spared-years-blizzard-1978-77397

https://web.archive.org/web/20160612043501/http://indianapublicmedia.org/news/indy-500-cash-prize-visualized-99704/

https://web.archive.org/web/20160601121430/http://indianapublicmedia.org/news/woman-dies-swimming-cataract-falls-99696/

https://web.archive.org/web/20170325085341/http://indianapublicmedia.org/news/study-transport-snake-turtle-99691/

**Comment by aaronburatti** [comment]
This is going to have to wait a while

**Comment by aaronburatti** [comment]
Update 6/8: The story links that used to 404 are now eliminated. This ticket has transformed into an issue of there being stories that should be archived that aren't. I hope that as i re-import pages into Cascade this will resolve itself. We will check back in on this one.

**Comment by aaronburatti** [comment]
resolved
