### ISSUE TITLE
/news/ date archives display incorrect/duplicate month names

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#192]
Some date archive years display months like "Jan Mar Mar May May Jul Jul..."

Examples:

https://indianapublicmedia.org/archive/news/news-archive-2016-1.php
https://indianapublicmedia.org/archive/news/news-archive-2015-1.php
https://indianapublicmedia.org/archive/news/news-archive-2014-1.php

**Comment by aaronburatti** [comment]
fixed
