### ISSUE TITLE
/eartheats/ older segments missing photos when shown in 'stories on episode'

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#193]
Older segments are missing their photo when shown in 'stories on this episode'. Examples:

https://indianapublicmedia.org/eartheats/food-stamps-farm-policydoes-marriage-sense.php
https://indianapublicmedia.org/eartheats/yeast-hunting.php

**Comment by eobanb** [comment]
Of all the recent EE things to look at, this is probably the hardest to fix and also one of the least-important, so it can be further down on the priority list.

**Comment by aaronburatti** [comment]
These older episodes had the "Stories in this Section" embedded in the rich text formatter, not the data definition. Therefore they cannot import the image
