### ISSUE TITLE
/eartheats/ improve blockquote styling

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#194]
Pullquotes have been converted to a <blockquote> combination, but styling is not optimal. Examples:

https://indianapublicmedia.org/eartheats/day-adventure-inkwell-bakery.php
https://indianapublicmedia.org/eartheats/midwest-recruiting-ca-dairies-pump-rural-economy.php

**Comment by aaronburatti** [comment]
@eobanb What is a better styling for this?

**Comment by eobanb** [comment]
See the original styling these had here:

https://web.archive.org/web/20150122090239/https://indianapublicmedia.org/eartheats/midwest-recruiting-ca-dairies-pump-rural-economy/

**Comment by aaronburatti** [comment]
resolved
