### ISSUE TITLE
/eartheats/ some stories missing from date archives

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#196]
A number of stories are published, yet not appearing in the date archives. Example:

https://indianapublicmedia.org/eartheats/falafel-pita-fast-food-histories-black-communities.php
should be in
https://indianapublicmedia.org/archive/eartheats/eartheats-archive-2019-3.php
(a dozen or more stories are missing from March 2019 archive, and others)

**Comment by aaronburatti** [comment]
This is closed and actually, the format I wrote solved another problem that was lurking in the background. We used to have two formats, on for archive pages from .main and another from cold storage. When archive pages are created automatically every month they came attached with the format for drawing pages from the .main site. As stories aged and they were moved automatically to the cold storage sites they became invisible. With this new format unifying the .main and cold storage several problems across several sections are solved at once
