### ISSUE TITLE
/eartheats/ strange chars

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#197]
Similar `â€™` character issue as AMOS/NL.
Examples:
https://indianapublicmedia.org/eartheats/muddy-forks-spelt-pita-bread.php
https://indianapublicmedia.org/eartheats/muddy-forks-pizza-dough.php
Similar, but different character sequence `(Â®):`
https://indianapublicmedia.org/eartheats/apple-pie-filling-for-canning.php
Another `(â€”)` sequence:
https://indianapublicmedia.org/eartheats/faux-cheddar-hour.php

**Comment by eobanb** [comment]
This mainly seems to affect recipes.

**Comment by aaronburatti** [comment]
fixed
