### ISSUE TITLE
/justyouandme/ - design update

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#202]
DBJ is starting a Just You and Me blog; JYM's front page should be changed to display 'Recent Playlists' and 'Blog' in a pair of columns (underneath the existing 'About' areas). Essentially this should be the same as lower half of the /nightlights/ index page:

Left column: 18-20 recent playlists, essentially the same as currently but in a narrower column

Right column: 3-4 recent blog posts (posts categorized as 'blog')

**Comment by aaronburatti** [comment]
When is this going live?

**Comment by eobanb** [comment]
I am checking with DBJ on the status of blog posts, but should be this week.

**Comment by eobanb** [comment]
DBJ has said his first two blog posts will be ready to publish on Monday, Mar 2 (one week from today)—so let's please plan on that date to go live.

**Comment by aaronburatti** [comment]
Abandoned by content creator
