### ISSUE TITLE
/journeyindiana/ map embed

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#212]
JI is to have a embedded map (Google or otherwise) of various stories, akin to the from Weekly Special. Some technical research needed here.

**Comment by eobanb** [comment]
Developing this with Flourish for now.

**Comment by eobanb** [comment]
Whew, nearly done.

https://public.flourish.studio/visualisation/3371096/

**Comment by aaronburatti** [comment]
I believe this is done
