### ISSUE TITLE
/focusonflowers/ older mp3 paths must be updated

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#216]
Older mp3 file paths read `wfiu.indiana.edu` and should be changed to `indianapublicmedia.org`. Most/all posts before about July 2017 are affected and audio does not play. Example:

https://indianapublicmedia.org/focusonflowers/years.php

**Comment by eobanb** [comment]
This doesn't seem to be fixed yet, as many posts still do not play (and have wfiu.indiana.edu for the hostname in mp3 path). Examples:

https://indianapublicmedia.org/focusonflowers/red-chokeberry.php

https://indianapublicmedia.org/focusonflowers/hyacinth-glass.php

https://indianapublicmedia.org/focusonflowers/blue.php

https://indianapublicmedia.org/focusonflowers/chartreuse.php

https://indianapublicmedia.org/focusonflowers/plant-origins.php

https://indianapublicmedia.org/focusonflowers/carpeting-plants.php

**Comment by aaronburatti** [comment]
Should be good

**Comment by eobanb** [comment]
This is not solved yet.

Examples:

https://indianapublicmedia.org/focusonflowers/bumblebee-brains.php

https://indianapublicmedia.org/focusonflowers/february.php

https://indianapublicmedia.org/focusonflowers/twelfth-night.php

https://indianapublicmedia.org/focusonflowers/vertical-accents.php

https://indianapublicmedia.org/focusonflowers/garden-hyacinth.php

https://indianapublicmedia.org/focusonflowers/daffodil-classification.php

https://indianapublicmedia.org/focusonflowers/dogbane.php

https://indianapublicmedia.org/focusonflowers/bad-bees.php

https://indianapublicmedia.org/focusonflowers/baby-mums.php

https://indianapublicmedia.org/focusonflowers/rhymes-kids.php

https://indianapublicmedia.org/focusonflowers/vitas-view.php

https://indianapublicmedia.org/focusonflowers/quotable-quotes.php

**Comment by aaronburatti** [comment]
This is resolved

**Comment by eobanb** [comment]
Thank you! I did some spot checks and this does seem to be resolved now.
