### ISSUE TITLE
/nightlights/ many older posts missing image

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#217]
Examples:

https://indianapublicmedia.org/nightlights/ella-57-ella-fitzgerald-flies-high.php

https://indianapublicmedia.org/nightlights/glenn-miller-war-army-air-force-band.php

https://indianapublicmedia.org/nightlights/bebop-europe.php

https://indianapublicmedia.org/nightlights/hope-lives-portrait-elmo-hope.php

https://indianapublicmedia.org/nightlights/hipsters-flipsters-onthescenesters.php

https://indianapublicmedia.org/nightlights/boppin-bee-hive.php

https://indianapublicmedia.org/nightlights/fusion-jazzrock-bitches-brew.php

https://indianapublicmedia.org/nightlights/crossing-bridge-return-sonny-rollins.php

https://indianapublicmedia.org/nightlights/great-columbia-jazz-purge-coleman-evans-jarrett-mingus.php

**Comment by aaronburatti** [comment]
Should be resolved
