### ISSUE TITLE
/news/ topic labels for series posts

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#223]
Posts that are part of a topic series (I.e. that appear on a topic page) should be able to display a box/banner of some kind that labels that post as being part of a series.

Example from NPR with a similar idea:

<img width="1089" alt="Screen Shot 2020-04-02 at 10 47 19" src="https://user-images.githubusercontent.com/607060/78263009-66cd3c00-74cf-11ea-8dc0-738987003ae8.png">

**Comment by aaronburatti** [comment]
resolved
