### ISSUE TITLE
lazy image loading

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#225]
A new HTML attribute called `loading` allows browsers to lazy-load images without the aid of javascript when the value is set to `loading="lazy"`.

Since this is now relatively widely-supported (see https://caniuse.com/#feat=loading-lazy-attr ), it is now worth implementing to improve load times of pages with several large images (which on our site is many).

index pages, topic pages, etc should be prioritized as these usually have many images compared to individual posts.

**Comment by aaronburatti** [comment]
Update: most of these formats have been updated

**Comment by aaronburatti** [comment]
Should be good
