### ISSUE TITLE
/indiandroid/ - misc. fixes

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#229]
Index:

Needs some visual improvements on mobile (namely, featured image is much too large) Also image and headline for featured / latest story should be link to click through to story.

Sub-pages:

sub-pages 'Videos' and 'Extras' most recent content is from March 2019. Do these need to be periodically republished?

**Comment by aaronburatti** [comment]
The responsiveness and link issue is fixed.

The data on the pages inside cascade is the same as the published pages. I just think there hasn't been a lot of new stuff to publish here
