### ISSUE TITLE
main index pages - minor fixes

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#231]
Longer titles can cause certain text to wrap in a funny way; see screenshot.

<img width="299" alt="Screen Shot 2020-06-04 at 09 14 22" src="https://user-images.githubusercontent.com/607060/83761201-00d27180-a644-11ea-91a1-b2a3f7e9a1e3.png">

**Comment by eobanb** [comment]
Another index page issue: odd character appearing (`Â`) in some places.

<img width="163" alt="Screen Shot 2020-06-04 at 09 16 41" src="https://user-images.githubusercontent.com/607060/83761321-28c1d500-a644-11ea-9985-918721f0039a.png">

**Comment by aaronburatti** [comment]
resolved
