### ISSUE TITLE
Photos not displaying properly in  "Stories in this Episode"

### ISSUE THREAD

**Issue by kayte8** [indianapublicmedia/indianapublicmedia-web#25]
At the bottom of the podcast posts, the section that includes the linked stories, "Stories in the Episode" the photos are not displaying properly. My work around for the most recent episodes is to have links for tose stories in the body of the post. But for all the older podcast posts, the problem is visible.

**Comment by eobanb** [comment]
This is fixed now. (Example: https://indianapublicmedia.org/eartheats/food-assistancethree-ways/ )

**Comment by kayte8** [comment]
?Fantastic! Thank you.


Kayte Young
Producer of Earth Eats<http://indianapublicmedia.org/eartheats/>
<http://indianapublicmedia.org/eartheats/>
Multimedia Producer-WFIU
Indiana University
Bloomington, Indiana
younka@iu.edu

________________________________
