### ISSUE TITLE
Unable to subscribe to Podcasts on Apple

### ISSUE THREAD

**Issue by mchilla** [indianapublicmedia/indianapublicmedia-web#27]
This is sort of a follow-up to issues #19 and #26, but when you search for WFIU podcasts (like Earth Eats and Profiles) in the podcast app, the latest episodes show up and will play. However, if you try to SUBSCRIBE to them it says "Unable To Subscribe: Podcast cannot be added because the server or feed cannot be found." This may be why podcasts haven't been showing up for people who were _already_ subscribed.

**Comment by eobanb** [comment]
This is fixed now.
