### ISSUE TITLE
misc - small issues to be fixed with /classical, /soulkitchen, /sylvia

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#321]
~~- Header graphics not appearing on archives; example: https://indianapublicmedia.org/archive/soulkitchen/archive-2021.php~~

~~- Top h3 headers and DFP creative should be visually aligned vertically:~~

<img width="509" alt="Screen Shot 2021-02-26 at 13 02 52" src="https://user-images.githubusercontent.com/607060/109338353-289de100-7834-11eb-99c1-b2614526ac3c.png">

~~- REMOVE: 'About' link on all 3 sites desktop+mobile navigation~~

~~- Archive pages do not show '2021' next to 'Year:'; example: https://indianapublicmedia.org/archive/sylvia/archive-2021.php~~

~~- existing web posts for all 3 sections display 'Aaron Buratti' as author instead of William Morris; example: https://indianapublicmedia.org/classical/february-8th-2021.php~~

~~- /about/contact.php page needs dropdown reasons for Sylvia, Classical, and Soul Kitchen; example:  https://indianapublicmedia.org/about/contact.php?reason=sylvia~~

**Comment by aaronburatti** [comment]
Resolved
