### ISSUE TITLE
excerpt field missing on 'Indiana Newsdesk' page

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#33]
Joe can no longer update the excerpt on the Indiana Newsdesk page. Now, a description is auto-filled in the "SEO package" section. It's a 2-week old description and cannot be edited.

**Comment by eobanb** [comment]
Can he edit the value of the teaser_text custom field? (look down at the Custom Fields box)

**Comment by rebmthom** [comment]
I think so. We went to look but you're in it right now.

**Comment by eobanb** [comment]
Oops, closed out now.

**Comment by rebmthom** [comment]
Yes, that worked.

**Comment by eobanb** [comment]
Yeah I forgot that pages don't have an excerpt field by default. I think by and large excerpts will be on posts, Newsdesk being one exception...so in the case of this page let's just edit that custom field for now.
