### ISSUE TITLE
/tv/ - page layout problems on large mobile breakpoint

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#331]
Two issues going on here: appearance of rotator, and misalignment of two 300x250 creatives below. See attached screenshot:

<img width="944" alt="Screen Shot 2021-04-06 at 14 49 43" src="https://user-images.githubusercontent.com/607060/113763790-18590b80-96e8-11eb-91c4-77565dbc0e87.png">

**Comment by aaronburatti** [comment]
resolved
