### ISSUE TITLE
/amomentofscience/ - image credit links broken

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#334]
Example:

https://indianapublicmedia.org/amomentofscience/ants-and-superstrength.php

Format outputs the link as: `https://indianapublicmedia.org/amomentofscience/%7Bhttps://www.flickr.com/photos/atoll/2914942715.....`

**Comment by eobanb** [comment]
Note: this may affect other sections too besides AMOS.

**Comment by aaronburatti** [comment]
resolved
