### ISSUE TITLE
old audio not playing on the site

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#34]
I obviously haven't checked every post, but many I've checked are not working, both before we switched away from wfiu.indiana.edu and after:

https://indianapublicmedia.org/news/crowded-field-challenging-indianas-9th-district-incumbent-145126/

https://indianapublicmedia.org/news/dnr-trains-residents-fight-invasive-asian-carp-population-124057/

https://indianapublicmedia.org/news/bosma-center-116685/

**Comment by eobanb** [comment]
This is fixed now...happened because of a js library upgrade we made yesterday.
