### ISSUE TITLE
photo thumbnails for stories after 3/12 are not populating on 2018 primary election pages

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#35]
Photo thumbnails for stories before the website went down DO show up, but new ones do not. Here are all of the pages, even though many of them don't have any recent stories to illustrate the problem:

https://indianapublicmedia.org/election/2018-primary/local-races/

https://indianapublicmedia.org/election/2018-primary/state-house-democrats/

https://indianapublicmedia.org/election/2018-primary/state-house-republicans/

https://indianapublicmedia.org/election/2018-primary/state-senate-democrats/

https://indianapublicmedia.org/election/2018-primary/state-senate-republicans/

https://indianapublicmedia.org/election/2018-primary/us-house-democrats/

https://indianapublicmedia.org/election/2018-primary/us-house-republicans/

https://indianapublicmedia.org/election/2018-primary/us-senate-republicans/

**Comment by eobanb** [comment]
This is fixed now.
