### ISSUE TITLE
Breaking news tag not functional 

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#44]

**Comment by eobanb** [comment]
This may be problematic to address due to how cascade updates/publishes pages, but we'll discuss.

**Comment by aaronburatti** [comment]
What should the functionality be here?

**Comment by eobanb** [comment]
I'll talk about this with news...it may have to be implemented using BTi so that things actually show up and disappear in a timely fashion (independently of a page being published).

**Comment by eobanb** [comment]
Merging with #57
