### ISSUE TITLE
sitewide: NPR Story API web service / NPR One

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#45]
if that's even possible.

**Comment by eobanb** [comment]
In October we'll be going to a conference to learn more about Cascade web services. Our hope is to use a Cascade web service with PMP and/or the NPR API.

**Comment by eobanb** [comment]
I'm giving up on this until the mythical Brightspot CMS migration

**Comment by aaronburatti** [comment]
@eobanb I'm not sure its necessary to give up on this. Its never been presented as a priority and there has always been more pressing stuff. If we have our station API key then it should be possible

**Comment by eobanb** [comment]
`¯\_(ツ)_/¯`

**Comment by aaronburatti** [comment]
Yeah, i know. I don't have the API key laying around anywhere though. Can you recover it?

**Comment by aaronburatti** [comment]
This is operational. I'm closing this ticket and we can open new ones for new functionality
