### ISSUE TITLE
Author pages not working

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#46]
Need author tags to link to pages with that reporter's other work.

**Comment by aaronburatti** [comment]
Will this only be for current staff, i.e. excluding interns, and agencies? Should it essentially look like this: https://indianapublicmedia.org/cafeindiana/author/yksander/ but with the right page header? Also, specifically for you @rebmthom, just like everything else someone will have to stay on top of republishing it all the time. I don't think we'll be able to make each author's archive available to themselves

**Comment by rebmthom** [comment]
For current staff, although I like the idea of leaving them active even when people leave. Could we just categorize those usernames as "inactive"? We don't need them for interns or agencies. 

Here's an example of a news one: https://indianapublicmedia.org/news/author/rebmthom/ 

I can take care of republishing those pages all the time. It's annoying, but at this point I can just make it a daily activity to republish the 700 pages that need it.

**Comment by eobanb** [comment]
We'll consolidate all these in a single folder (I.e. /user-profiles/rebmthom.php ) so that they're not strewn across a bunch of separate areas. Then it'll just be a matter of re-publishing a folder to keep them all updated. Plus inactive users don't clutter up things as much.

**Comment by aaronburatti** [comment]
I am about 75% through this. i have the page mostly set up and the fields set up correctly except for the author field. inconsistency on authors part in the way posts are attributed will take some creativity

**Comment by aaronburatti** [comment]
This is ready to be launched
