### ISSUE TITLE
News articles not categorized under "News" section for Chartbeat

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#50]
TOP PRIORITY (jk)

**Comment by eobanb** [comment]
This will need to be fixed by specifying some variables for the chartbeat config, namely...

` _sf_async_config.sections = '/news/'; _sf_async_config.authors = 'news';`

**Comment by aaronburatti** [comment]
Resolved. I believe. Will wait to close this ticket until confirmation

**Comment by eobanb** [comment]
This does appear to be resolved now (in Chartbeat I see traffic specifically for /news/ .

**Comment by eobanb** [comment]
@rebmthom please let us know if you're still having any Chartbeat issues.

**Comment by rebmthom** [comment]
I don't see the right traffic for /news/ in Chartbeat. All I see is old articles that are on Wordpress.

**Comment by eobanb** [comment]
We may need to re-publish the /news/ section so that the appropriate code is added to posts that have already been published. Remember that any change we make requires re-publishing to affect older content.
