### ISSUE TITLE
sitewide: resurrect rss/atom output (incl podcast rss)

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#51]

**Comment by aaronburatti** [comment]
pending review  https://indianapublicmedia.org/feeds/news-all.xml    https://indianapublicmedia.org/feeds/news-audio.xml

**Comment by aaronburatti** [comment]
This should be conluded

**Comment by eobanb** [comment]
A few things to re-visit on this, so keeping open for the moment. Bumping down the priority list though.

**Comment by eobanb** [comment]
Note to self: test Ask The Mayor

**Comment by eobanb** [comment]
@aaronburatti so here's a fun one....

We will need a podcast RSS feed for Ask The Mayor; however, these posts don't have their own content type, they're just News posts. Basically, a podcast RSS feed mirroring the posts that show up on this page:

https://indianapublicmedia.org/news/topics/ask-the-mayor.php

**Comment by aaronburatti** [comment]
I feel like we can confidently close this issue because we have valid feeds
