### ISSUE TITLE
need way to exclude staff/inside bldg folks from google analytics

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#52]

**Comment by eobanb** [comment]
This will probably be accomplished with Google Analytics Filters, but I'll look into it more.

**Comment by eobanb** [comment]
After giving this some thought, we're going to do a two-tier approach here by moving GA to a php include so that it never loads in Cascade, and secondarily set up an IP range filter.

**Comment by eobanb** [comment]
After some more research still, we're just doing an IP range filter in GA (as this can be set more or less permanently). This is effective as of today (Jan 10, 2019). I've annotated GA for this date as well.
