### ISSUE TITLE
sitewide: implement publish sets (and base workflows for publish/delete)

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#57]
A number of pages need to be re-published consistently:

front pages
archive pages
author pages
a small set of category/special pages

**Comment by eobanb** [comment]
Refocusing on this a bit; this is going to be solved with Publish Sets instead of web services. More to come.

**Comment by eobanb** [comment]
In the scope of this issue is breaking news banners for front page.

**Comment by aaronburatti** [comment]
The publishing aspect of this has been accessed through the Service Provider base class
