### ISSUE TITLE
/email/ fix saturday news template

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#58]
Top story does not appear correctly on certain email clients. This design needs to be fixed/simplified in order to avoid this problem

**Comment by eobanb** [comment]
@aaronburatti part of the problem with this template is headlines get output with double-escaped single quote / apostrophe characters, as in:

`Watch &apos;Indiana Newsdesk:&apos; Employer Drug Tests, Trevor&apos;s Law`

Can you fix? I will take care of other visual issues (css, etc)

**Comment by aaronburatti** [comment]
Sure. Looking at it now

**Comment by eobanb** [comment]
Actually, never mind, I think I fixed it.

**Comment by aaronburatti** [comment]
Good deal
