### ISSUE TITLE
sitewide: create option to exclude post from google search

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#61]

**Comment by eobanb** [comment]
I think what we'll do is just use the noindex meta tag, as documented here:

https://support.google.com/webmasters/answer/93710?hl=en

**Comment by eobanb** [comment]
Aaron, let's aim to have this one done by Friday, Jan 25.

**Comment by aaronburatti** [comment]
in production and ready for use on all main pages
