### ISSUE TITLE
Google Analytics: custom dimensions (author, etc)

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#62]

**Comment by eobanb** [comment]
Aaron, I'll research this a bit first and then we'll discuss. I suspect we'll set up a custom dimension in Google Analytics, but not 100% sure yet.

**Comment by eobanb** [comment]
I've set this up as a custom dimension in GA....see:

https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

@aaronburatti , Cascade will need to output this JS for each page:

var dimensionValue = 'ebinder';
ga('set', 'dimension1', dimensionValue);

...where ebinder is the author page name set for a page. If a guest author is set instead, just output that string.

**Comment by eobanb** [comment]
Note: only output this dimension for posts. For all other pages (home pages, about pages, etc) do not output, otherwise this will create a lot of spurious data in GA

**Comment by eobanb** [comment]
This is still not working. @aaronburatti can you try this instead?

`ga(‘send’, ‘pageview’, {
 ‘dimension1’:  ‘Name Here’
});`

**Comment by aaronburatti** [comment]
I have this:  ga('station1.set', 'dimension1', '${postAuthor}'); in there now

**Comment by eobanb** [comment]
I am re-working how we are going to do this again... working with NPR Digital Services on this now.

**Comment by eobanb** [comment]
Just a quick update; this is still an open issue with NPR DS.

**Comment by eobanb** [comment]
Finally got this working too...whew.
