### ISSUE TITLE
sitewide: implement hidden/internal edit links

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#66]
Mockup at https://indianapublicmedia.org/news/index-beta.php

**Comment by eobanb** [comment]
@aaronburatti , your part in this is just to make sure Cascade outputs the page's internal Cascade link in the href attribute of the edit link. My part will be implementing the CAS / browser cookie part so the edit link only appears to the correct users.

**Comment by aaronburatti** [comment]
The cascade side of this is done

**Comment by eobanb** [comment]
Done.
