### ISSUE TITLE
hide related posts, recent stories, read next, etc from googlebot

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#68]
Google site search results ordered by date routinely show irrelevant results due to indexing of 'related posts' and/or 'read next' headlines as part of a page's content.

These should be hidden from googlebot using a PHP that detects user-agent string, and then conditionally prints the markup.

**Comment by eobanb** [comment]
Note: to implement only on single posts...not archive pages, home pages, topic pages, etc

**Comment by eobanb** [comment]
Something along the lines of this:

https://stackoverflow.com/questions/677419/how-to-detect-search-engine-bots-with-php

**Comment by aaronburatti** [comment]
i tried one of these things. We'll see how well it works

**Comment by eobanb** [comment]
I've run a few searches and this seems to be working, yay.
