### ISSUE TITLE
Google Analytics: group posts by category and/or tag

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#69]
(like Inquire Indiana, Indiana Newsdesk, etc.)

**Comment by eobanb** [comment]
@rebmthom GA has a feature called 'Content Grouping', but it's limited to five content groups at any one time per view (or maybe it's per property, not sure).

https://support.google.com/analytics/answer/2853423?hl=en

Another option is to use a Custom Dimension:

https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

This is probably also how we would implement viewing by author...

**Comment by eobanb** [comment]
We're going to prototype this with authors first and if it seems to work we'll figure it out for topics/tags/categories .

**Comment by eobanb** [comment]
Merging with #62
