### ISSUE TITLE
/about/ : set user profiles to show 20 recent posts, then a link to google site search

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#78]
Some users publish a lot of content; to avoid overloading their profile pages, only show 20 posts, then link to a google site search at the bottom for firstname+lastname, ordered by date. For example:

https://indianapublicmedia.org/search/?cx=002327456492095995457%3Aatgbv6ivl-g&cof=FORID%3A9&ie=UTF-8&q=becca+costello&sa=Search&siteurl=indianapublicmedia.org%2Fsearch%2F%3Fq%3Dbecca%2Bcostello&ref=&ss=

**Comment by aaronburatti** [comment]
implemented
