### ISSUE TITLE
/, /radio/, /tv/ standardize carousel image padding

### ISSUE THREAD

**Issue by aaronburatti** [indianapublicmedia/indianapublicmedia-web#81]
On certain images there is a bit more padding between the image and the text than with others

**Comment by eobanb** [comment]
`object-fit:cover` is my friend, your friend, and everyone else's too.

**Comment by aaronburatti** [comment]
I added this, and I'm pretty sure it was already styled that way. There is an AMOS article about magensite on the rotator and the padding issue remains still. Further investigation needed

**Comment by aaronburatti** [comment]
I believe this is fixed, also the font-sizing and padding is now uniform

**Comment by aaronburatti** [comment]
Hopefully for the last time
