### ISSUE TITLE
/indianamatters/ contact form

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#84]
Contact form needed for Indiana Matters that goes to Beth Edwards and David González. Three fields needed: Name, Email, Question (all three required).

**Comment by aaronburatti** [comment]
Is there a deadline with this?

**Comment by eobanb** [comment]
Let's say by end of next week (Feb 15).

**Comment by aaronburatti** [comment]
Just need to know the recipient email address and this is ready to go
