### ISSUE TITLE
/news/ topics pages - create option for number of 'read more' stories

### ISSUE THREAD

**Issue by eobanb** [indianapublicmedia/indianapublicmedia-web#88]
Some news topics pages need more stories to be shown under 'read more', others fewer. We should create an option to set a custom number of posts (or, when no number is filled in, default to, say, 20).

**Comment by eobanb** [comment]
@aaronburatti can this be looked at by the end of next week (Apr 12)?

**Comment by aaronburatti** [comment]
This feature is implemented
