### ISSUE TITLE
Files greater than 2 MB cannot be uploaded to WP media library

### ISSUE THREAD

**Issue by rebmthom** [indianapublicmedia/indianapublicmedia-web#9]
It only happens to some photos and I can't figure out a pattern. All are JPGs and the error photos aren't any bigger than others I'm uploading. 

Not a big priority cause I can choose other photos in the meantime.

**Comment by eobanb** [comment]
I suspect it's a file size issue. Can you check the file size of ones that are erroring?

**Comment by rebmthom** [comment]
It's happened to two so far. Both are about 2,000 pixels wide, and I've been able to upload photos larger than that with no problem. But maybe it is the size and it's just an error sometimes?

**Comment by eobanb** [comment]
File size is independent of image resolution, so I just need to know file sizes.

**Comment by rebmthom** [comment]
lol sorry. learning new things every day. 

2,062 KB and 2,057 KB.

**Comment by eobanb** [comment]
Becca, try it again. There was a 2 MB limit set for upload file size. It's been increased to 32 MB now.

**Comment by rebmthom** [comment]
I tried again but same message. I also logged out of Wordpress and back in and got the same error.

**Comment by eobanb** [comment]
I've emailed Dan about this again to see what's going on.
